package dhnetsdk

// #cgo CFLAGS: -Iinclude/
// #cgo amd64 386 CFLAGS: -DX86=1
// #cgo LDFLAGS: -Llib/ -ldhnetsdk -lpthread -Wl,-rpath=./lib/
// #include <stdio.h>
// #include <stdlib.h>
// #include <string.h>
// #include <stdbool.h>
// #include "dhnetsdk.h"
import "C"

type EmLoginSpacCapType int

type DhAlarmType int

const (
	// 报警类型,对应CLIENT_StartListen接口
	DhCommAlarm         DhAlarmType = C.DH_COMM_ALARM          // 常规报警(包括外部报警,视频丢失,动态检测)
	DhShelterAlarm      DhAlarmType = C.DH_SHELTER_ALARM       // 视频遮挡报警
	DhDiskFullAlarm     DhAlarmType = C.DH_DISK_FULL_ALARM     // 硬盘满报警
	DhDiskErrorAlarm    DhAlarmType = C.DH_DISK_ERROR_ALARM    // 硬盘故障报警
	DhSoundDetectAlarm  DhAlarmType = C.DH_SOUND_DETECT_ALARM  // 音频检测报警
	DhAlarmDecoderAlarm DhAlarmType = C.DH_ALARM_DECODER_ALARM // 报警解码器报警
)

const (
	EmLoginSpecCapTcp            EmLoginSpacCapType = 0  // TCP登陆 默认方式
	EmLoginSpecCapAny            EmLoginSpacCapType = 1  // 无条件登陆
	EmLoginSpecCapServerConn     EmLoginSpacCapType = 2  // 主动注册的登入
	EmLoginSpecCapMulticast      EmLoginSpacCapType = 3  // 组播登陆
	EmLoginSpecCapUdp            EmLoginSpacCapType = 4  // UDP方式下的登入
	EmLoginSpecCapMainConnOnly   EmLoginSpacCapType = 6  // 只建主连接下的登入
	EmLoginSpecCapSsl            EmLoginSpacCapType = 7  // SSL加密方式登陆
	EmLoginSpecCapIntelligentBox EmLoginSpacCapType = 9  // 登录智能盒远程设备
	EmLoginSpecCapNoConfig       EmLoginSpacCapType = 10 // 登录设备后不做取配置操作
	EmLoginSpecCapULogin         EmLoginSpacCapType = 11 // 用U盾设备的登入
	EmLoginSpecCapLdap           EmLoginSpacCapType = 12 // LDAP方式登录
	EmLoginSpecCapAd             EmLoginSpacCapType = 13 // AD（ActiveDirectory）登录方式
	EmLoginSpecCapRadius         EmLoginSpacCapType = 14 // Radius 登录方式
	EmLoginSpecCapSocket_5       EmLoginSpacCapType = 15 // Socks5登陆方式
	EmLoginSpecCapCloud          EmLoginSpacCapType = 16 // 云登陆方式
	EmLoginSpecCapAuthTwice      EmLoginSpacCapType = 17 // 二次鉴权登陆方式
	EmLoginSpecCapTs             EmLoginSpacCapType = 18 // TS码流客户端登陆方式
	EmLoginSpecCapP2P            EmLoginSpacCapType = 19 // 为P2P登陆方式
	EmLoginSpecCapMobile         EmLoginSpacCapType = 20 // 手机客户端登陆
	EmLoginSpecCapInvalid        EmLoginSpacCapType = 21 // 无效的登陆方式
)

type EventIvs int

const (
	EventIvsAll                          EventIvs = C.EVENT_IVS_ALL                           // 订阅所有事件
	EventIvsCrosslinedetection           EventIvs = C.EVENT_IVS_CROSSLINEDETECTION            // 警戒线事件(对应 DEV_EVENT_CROSSLINE_INFO)
	EventIvsCrossregiondetection         EventIvs = C.EVENT_IVS_CROSSREGIONDETECTION          // 警戒区事件(对应 DEV_EVENT_CROSSREGION_INFO)
	EventIvsPastedetection               EventIvs = C.EVENT_IVS_PASTEDETECTION                // 贴条事件(对应 DEV_EVENT_PASTE_INFO)
	EventIvsLeftdetection                EventIvs = C.EVENT_IVS_LEFTDETECTION                 // 物品遗留事件(对应 DEV_EVENT_LEFT_INFO)
	EventIvsStaydetection                EventIvs = C.EVENT_IVS_STAYDETECTION                 // 停留事件(对应 DEV_EVENT_STAY_INFO)
	EventIvsWanderdetection              EventIvs = C.EVENT_IVS_WANDERDETECTION               // 徘徊事件(对应 DEV_EVENT_WANDER_INFO)
	EventIvsPreservation                 EventIvs = C.EVENT_IVS_PRESERVATION                  // 物品保全事件(对应 DEV_EVENT_PRESERVATION_INFO)
	EventIvsMovedetection                EventIvs = C.EVENT_IVS_MOVEDETECTION                 // 移动事件(对应 DEV_EVENT_MOVE_INFO)
	EventIvsTaildetection                EventIvs = C.EVENT_IVS_TAILDETECTION                 // 尾随事件(对应 DEV_EVENT_TAIL_INFO)
	EventIvsRioterdetection              EventIvs = C.EVENT_IVS_RIOTERDETECTION               // 聚众事件(对应 DEV_EVENT_RIOTERL_INFO)
	EventIvsFiredetection                EventIvs = C.EVENT_IVS_FIREDETECTION                 // 火警事件(对应 DEV_EVENT_FIRE_INFO)
	EventIvsSmokedetection               EventIvs = C.EVENT_IVS_SMOKEDETECTION                // 烟雾报警事件(对应 DEV_EVENT_SMOKE_INFO)
	EventIvsFightdetection               EventIvs = C.EVENT_IVS_FIGHTDETECTION                // 斗殴事件(对应 DEV_EVENT_FIGHT_INFO)
	EventIvsFlowstat                     EventIvs = C.EVENT_IVS_FLOWSTAT                      // 流量统计事件(对应 DEV_EVENT_FLOWSTAT_INFO)
	EventIvsNumberstat                   EventIvs = C.EVENT_IVS_NUMBERSTAT                    // 数量统计事件(对应 DEV_EVENT_NUMBERSTAT_INFO)
	EventIvsCameracoverddetection        EventIvs = C.EVENT_IVS_CAMERACOVERDDETECTION         // 摄像头覆盖事件(保留)
	EventIvsCameramoveddetection         EventIvs = C.EVENT_IVS_CAMERAMOVEDDETECTION          // 摄像头移动事件(保留)
	EventIvsVideoabnormaldetection       EventIvs = C.EVENT_IVS_VIDEOABNORMALDETECTION        // 视频异常事件(对应 DEV_EVENT_VIDEOABNORMALDETECTION_INFO)
	EventIvsVideobaddetection            EventIvs = C.EVENT_IVS_VIDEOBADDETECTION             // 视频损坏事件(保留)
	EventIvsTrafficcontrol               EventIvs = C.EVENT_IVS_TRAFFICCONTROL                // 交通管制事件(对应 DEV_EVENT_TRAFFICCONTROL_INFO)
	EventIvsTrafficaccident              EventIvs = C.EVENT_IVS_TRAFFICACCIDENT               // 交通事故事件(对应 DEV_EVENT_TRAFFICACCIDENT_INFO)
	EventIvsTrafficjunction              EventIvs = C.EVENT_IVS_TRAFFICJUNCTION               // 交通路口事件----老规则(对应 DEV_EVENT_TRAFFICJUNCTION_INFO)
	EventIvsTrafficgate                  EventIvs = C.EVENT_IVS_TRAFFICGATE                   // 交通卡口事件----老规则(对应 DEV_EVENT_TRAFFICGATE_INFO)
	EventTrafficsnapshot                 EventIvs = C.EVENT_TRAFFICSNAPSHOT                   // 交通抓拍事件(对应 DEV_EVENT_TRAFFICSNAPSHOT_INFO)
	EventIvsFacedetect                   EventIvs = C.EVENT_IVS_FACEDETECT                    // 人脸检测事件 (对应 DEV_EVENT_FACEDETECT_INFO)
	EventIvsTrafficjam                   EventIvs = C.EVENT_IVS_TRAFFICJAM                    // 交通拥堵事件(对应 DEV_EVENT_TRAFFICJAM_INFO)
	EventIvsTrafficNonmotorinmotorroute  EventIvs = C.EVENT_IVS_TRAFFIC_NONMOTORINMOTORROUTE  // 非机动车占机动车车道事件(对应 DEV_EVENT_TRAFFIC_NONMOTORINMOTORROUTE_INFO)
	EventIvsTrafficRunredlight           EventIvs = C.EVENT_IVS_TRAFFIC_RUNREDLIGHT           // 交通违章-闯红灯事件(对应 DEV_EVENT_TRAFFIC_RUNREDLIGHT_INFO)
	EventIvsTrafficOverline              EventIvs = C.EVENT_IVS_TRAFFIC_OVERLINE              // 交通违章-压车道线事件(对应 DEV_EVENT_TRAFFIC_OVERLINE_INFO)
	EventIvsTrafficRetrograde            EventIvs = C.EVENT_IVS_TRAFFIC_RETROGRADE            // 交通违章-逆行事件(对应 DEV_EVENT_TRAFFIC_RETROGRADE_INFO)
	EventIvsTrafficTurnleft              EventIvs = C.EVENT_IVS_TRAFFIC_TURNLEFT              // 交通违章-违章左转(对应 DEV_EVENT_TRAFFIC_TURNLEFT_INFO)
	EventIvsTrafficTurnright             EventIvs = C.EVENT_IVS_TRAFFIC_TURNRIGHT             // 交通违章-违章右转(对应 DEV_EVENT_TRAFFIC_TURNRIGHT_INFO)
	EventIvsTrafficUturn                 EventIvs = C.EVENT_IVS_TRAFFIC_UTURN                 // 交通违章-违章掉头(对应 DEV_EVENT_TRAFFIC_UTURN_INFO)
	EventIvsTrafficOverspeed             EventIvs = C.EVENT_IVS_TRAFFIC_OVERSPEED             // 交通违章-超速(对应 DEV_EVENT_TRAFFIC_OVERSPEED_INFO)
	EventIvsTrafficUnderspeed            EventIvs = C.EVENT_IVS_TRAFFIC_UNDERSPEED            // 交通违章-低速(对应 DEV_EVENT_TRAFFIC_UNDERSPEED_INFO)
	EventIvsTrafficParking               EventIvs = C.EVENT_IVS_TRAFFIC_PARKING               // 交通违章-违章停车(对应 DEV_EVENT_TRAFFIC_PARKING_INFO)
	EventIvsTrafficWrongroute            EventIvs = C.EVENT_IVS_TRAFFIC_WRONGROUTE            // 交通违章-不按车道行驶(对应 DEV_EVENT_TRAFFIC_WRONGROUTE_INFO)
	EventIvsTrafficCrosslane             EventIvs = C.EVENT_IVS_TRAFFIC_CROSSLANE             // 交通违章-违章变道(对应 DEV_EVENT_TRAFFIC_CROSSLANE_INFO)
	EventIvsTrafficOveryellowline        EventIvs = C.EVENT_IVS_TRAFFIC_OVERYELLOWLINE        // 交通违章-压黄线 (对应 DEV_EVENT_TRAFFIC_OVERYELLOWLINE_INFO)
	EventIvsTrafficDrivingonshoulder     EventIvs = C.EVENT_IVS_TRAFFIC_DRIVINGONSHOULDER     // 交通违章-路肩行驶事件(对应 DEV_EVENT_TRAFFIC_DRIVINGONSHOULDER_INFO)
	EventIvsTrafficYellowplateinlane     EventIvs = C.EVENT_IVS_TRAFFIC_YELLOWPLATEINLANE     // 交通违章-黄牌车占道事件(对应 DEV_EVENT_TRAFFIC_YELLOWPLATEINLANE_INFO)
	EventIvsTrafficPedestrainpriority    EventIvs = C.EVENT_IVS_TRAFFIC_PEDESTRAINPRIORITY    // 交通违章-礼让行人/斑马线行人优先事件(对应 DEV_EVENT_TRAFFIC_PEDESTRAINPRIORITY_INFO)
	EventIvsCrossfencedetection          EventIvs = C.EVENT_IVS_CROSSFENCEDETECTION           // 翻越围栏事件(对应 DEV_EVENT_CROSSFENCEDETECTION_INFO)
	EventIvsElectrosparkdetection        EventIvs = C.EVENT_IVS_ELECTROSPARKDETECTION         // 电火花事件(对应 DEV_EVENT_ELECTROSPARK_INFO)
	EventIvsTrafficNopassing             EventIvs = C.EVENT_IVS_TRAFFIC_NOPASSING             // 交通违章-禁止通行事件(对应 DEV_EVENT_TRAFFIC_NOPASSING_INFO)
	EventIvsAbnormalrundetection         EventIvs = C.EVENT_IVS_ABNORMALRUNDETECTION          // 异常奔跑事件(对应 DEV_EVENT_ABNORMALRUNDETECTION_INFO)
	EventIvsRetrogradedetection          EventIvs = C.EVENT_IVS_RETROGRADEDETECTION           // 人员逆行事件(对应 DEV_EVENT_RETROGRADEDETECTION_INFO)
	EventIvsInregiondetection            EventIvs = C.EVENT_IVS_INREGIONDETECTION             // 区域内检测事件(对应 DEV_EVENT_INREGIONDETECTION_INFO)
	EventIvsTakenawaydetection           EventIvs = C.EVENT_IVS_TAKENAWAYDETECTION            // 物品搬移事件(对应 DEV_EVENT_TAKENAWAYDETECTION_INFO)
	EventIvsParkingdetection             EventIvs = C.EVENT_IVS_PARKINGDETECTION              // 非法停车事件(对应 DEV_EVENT_PARKINGDETECTION_INFO)
	EventIvsFacerecognition              EventIvs = C.EVENT_IVS_FACERECOGNITION               // 人脸识别事件(对应 DEV_EVENT_FACERECOGNITION_INFO)
	EventIvsTrafficManualsnap            EventIvs = C.EVENT_IVS_TRAFFIC_MANUALSNAP            // 交通手动抓拍事件(对应 DEV_EVENT_TRAFFIC_MANUALSNAP_INFO)
	EventIvsTrafficFlowstate             EventIvs = C.EVENT_IVS_TRAFFIC_FLOWSTATE             // 交通流量统计事件(对应 DEV_EVENT_TRAFFIC_FLOW_STATE)
	EventIvsTrafficStay                  EventIvs = C.EVENT_IVS_TRAFFIC_STAY                  // 交通滞留事件(对应 DEV_EVENT_TRAFFIC_STAY_INFO)
	EventIvsTrafficVehicleinroute        EventIvs = C.EVENT_IVS_TRAFFIC_VEHICLEINROUTE        // 有车占道事件(对应 DEV_EVENT_TRAFFIC_VEHICLEINROUTE_INFO)
	EventAlarmMotiondetect               EventIvs = C.EVENT_ALARM_MOTIONDETECT                // 视频移动侦测事件(对应 DEV_EVENT_ALARM_INFO)
	EventAlarmLocalalarm                 EventIvs = C.EVENT_ALARM_LOCALALARM                  // 外部报警事件(对应 DEV_EVENT_ALARM_INFO)
	EventIvsPrisonerrisedetection        EventIvs = C.EVENT_IVS_PRISONERRISEDETECTION         // 看守所囚犯起身事件(对应 DEV_EVENT_PRISONERRISEDETECTION_INFO)
	EventIvsTrafficTollgate              EventIvs = C.EVENT_IVS_TRAFFIC_TOLLGATE              // 交通违章-卡口事件----新规则(对应 DEV_EVENT_TRAFFICJUNCTION_INFO)
	EventIvsDensitydetection             EventIvs = C.EVENT_IVS_DENSITYDETECTION              // 人员密集度检测(对应 DEV_EVENT_DENSITYDETECTION_INFO)
	EventIvsVideodiagnosis               EventIvs = C.EVENT_IVS_VIDEODIAGNOSIS                // 视频诊断结果事件(对应 NET_VIDEODIAGNOSIS_COMMON_INFO 和 NET_REAL_DIAGNOSIS_RESULT)
	EventIvsQueuedetection               EventIvs = C.EVENT_IVS_QUEUEDETECTION                // 排队检测报警事件(对应 DEV_EVENT_QUEUEDETECTION_INFO)
	EventIvsTrafficVehicleinbusroute     EventIvs = C.EVENT_IVS_TRAFFIC_VEHICLEINBUSROUTE     // 占用公交车道事件(对应 DEV_EVENT_TRAFFIC_VEHICLEINBUSROUTE_INFO)
	EventIvsTrafficBacking               EventIvs = C.EVENT_IVS_TRAFFIC_BACKING               // 违章倒车事件(对应 DEV_EVENT_IVS_TRAFFIC_BACKING_INFO)
	EventIvsAudioAbnormaldetection       EventIvs = C.EVENT_IVS_AUDIO_ABNORMALDETECTION       // 声音异常检测(对应 DEV_EVENT_IVS_AUDIO_ABNORMALDETECTION_INFO)
	EventIvsTrafficRunyellowlight        EventIvs = C.EVENT_IVS_TRAFFIC_RUNYELLOWLIGHT        // 交通违章-闯黄灯事件(对应 DEV_EVENT_TRAFFIC_RUNYELLOWLIGHT_INFO)
	EventIvsClimbdetection               EventIvs = C.EVENT_IVS_CLIMBDETECTION                // 攀高检测事件(对应 DEV_EVENT_IVS_CLIMB_INFO)
	EventIvsLeavedetection               EventIvs = C.EVENT_IVS_LEAVEDETECTION                // 离岗检测事件(对应 DEV_EVENT_IVS_LEAVE_INFO)
	EventIvsTrafficParkingonyellowbox    EventIvs = C.EVENT_IVS_TRAFFIC_PARKINGONYELLOWBOX    // 黄网格线抓拍事件(对应 DEV_EVENT_TRAFFIC_PARKINGONYELLOWBOX_INFO)
	EventIvsTrafficParkingspaceparking   EventIvs = C.EVENT_IVS_TRAFFIC_PARKINGSPACEPARKING   // 车位有车事件(对应 DEV_EVENT_TRAFFIC_PARKINGSPACEPARKING_INFO)
	EventIvsTrafficParkingspacenoparking EventIvs = C.EVENT_IVS_TRAFFIC_PARKINGSPACENOPARKING // 车位无车事件(对应 DEV_EVENT_TRAFFIC_PARKINGSPACENOPARKING_INFO)
	EventIvsTrafficPedestrain            EventIvs = C.EVENT_IVS_TRAFFIC_PEDESTRAIN            // 交通行人事件(对应 DEV_EVENT_TRAFFIC_PEDESTRAIN_INFO)
	EventIvsTrafficThrow                 EventIvs = C.EVENT_IVS_TRAFFIC_THROW                 // 交通抛洒物品事件(对应 DEV_EVENT_TRAFFIC_THROW_INFO)
	EventIvsTrafficIdle                  EventIvs = C.EVENT_IVS_TRAFFIC_IDLE                  // 交通空闲事件(对应 DEV_EVENT_TRAFFIC_IDLE_INFO)
	EventAlarmVehicleacc                 EventIvs = C.EVENT_ALARM_VEHICLEACC                  // 车载ACC断电报警事件(对应 DEV_EVENT_ALARM_VEHICLEACC_INFO)
	EventAlarmVehicleTurnover            EventIvs = C.EVENT_ALARM_VEHICLE_TURNOVER            // 车辆侧翻报警事件(对应 DEV_EVENT_VEHICEL_ALARM_INFO)
	EventAlarmVehicleCollision           EventIvs = C.EVENT_ALARM_VEHICLE_COLLISION           // 车辆撞车报警事件(对应 DEV_EVENT_VEHICEL_ALARM_INFO)
	EventAlarmVehicleLargeAngle          EventIvs = C.EVENT_ALARM_VEHICLE_LARGE_ANGLE         // 车载摄像头大角度扭转事件
	EventIvsTrafficParkingspaceoverline  EventIvs = C.EVENT_IVS_TRAFFIC_PARKINGSPACEOVERLINE  // 车位压线事件(对应 DEV_EVENT_TRAFFIC_PARKINGSPACEOVERLINE_INFO)
	EventIvsMultisceneswitch             EventIvs = C.EVENT_IVS_MULTISCENESWITCH              // 多场景切换事件(对应 DEV_EVENT_IVS_MULTI_SCENE_SWICH_INFO)
	EventIvsTrafficRestrictedPlate       EventIvs = C.EVENT_IVS_TRAFFIC_RESTRICTED_PLATE      // 受限车牌事件(对应 DEV_EVENT_TRAFFIC_RESTRICTED_PLATE)
	EventIvsTrafficOverstopline          EventIvs = C.EVENT_IVS_TRAFFIC_OVERSTOPLINE          // 压停止线事件(对应 DEV_EVENT_TRAFFIC_OVERSTOPLINE)
	EventIvsTrafficWithoutSafebelt       EventIvs = C.EVENT_IVS_TRAFFIC_WITHOUT_SAFEBELT      // 交通未系安全带事件(对应 DEV_EVENT_TRAFFIC_WITHOUT_SAFEBELT)
	EventIvsTrafficDriverSmoking         EventIvs = C.EVENT_IVS_TRAFFIC_DRIVER_SMOKING        // 驾驶员抽烟事件(对应 DEV_EVENT_TRAFFIC_DRIVER_SMOKING)
	EventIvsTrafficDriverCalling         EventIvs = C.EVENT_IVS_TRAFFIC_DRIVER_CALLING        // 驾驶员打电话事件(对应 DEV_EVENT_TRAFFIC_DRIVER_CALLING)
	EventIvsTrafficPedestrainrunredlight EventIvs = C.EVENT_IVS_TRAFFIC_PEDESTRAINRUNREDLIGHT // 行人闯红灯事件(对应 DEV_EVENT_TRAFFIC_PEDESTRAINRUNREDLIGHT_INFO)
	EventIvsTrafficPassnotinorder        EventIvs = C.EVENT_IVS_TRAFFIC_PASSNOTINORDER        // 未按规定依次通行(对应 DEV_EVENT_TRAFFIC_PASSNOTINORDER_INFO)
	EventIvsObjectDetection              EventIvs = C.EVENT_IVS_OBJECT_DETECTION              // 物体特征检测事件
	EventAlarmAnalogalarm                EventIvs = C.EVENT_ALARM_ANALOGALARM                 // 模拟量报警通道的报警事件(对应DEV_EVENT_ALARM_ANALOGALRM_INFO)
	EventIvsCrosslinedetectionEx         EventIvs = C.EVENT_IVS_CROSSLINEDETECTION_EX         // 警戒线扩展事件
	EventAlarmCommon                     EventIvs = C.EVENT_ALARM_COMMON                      // 普通录像
	EventAlarmVideoblind                 EventIvs = C.EVENT_ALARM_VIDEOBLIND                  // 视频遮挡事件(对应 DEV_EVENT_ALARM_VIDEOBLIND)
	EventAlarmVideoloss                  EventIvs = C.EVENT_ALARM_VIDEOLOSS                   // 视频丢失事件
	EventIvsGetoutbeddetection           EventIvs = C.EVENT_IVS_GETOUTBEDDETECTION            // 看守所下床事件(对应 DEV_EVENT_GETOUTBED_INFO)
	EventIvsPatroldetection              EventIvs = C.EVENT_IVS_PATROLDETECTION               // 巡逻检测事件(对应 DEV_EVENT_PATROL_INFO)
	EventIvsOndutydetection              EventIvs = C.EVENT_IVS_ONDUTYDETECTION               // 站岗检测事件(对应 DEV_EVENT_ONDUTY_INFO)
	EventIvsNoanswercall                 EventIvs = C.EVENT_IVS_NOANSWERCALL                  // 门口机呼叫未响应事件
	EventIvsStoragenotexist              EventIvs = C.EVENT_IVS_STORAGENOTEXIST               // 存储组不存在事件
	EventIvsStoragelowspace              EventIvs = C.EVENT_IVS_STORAGELOWSPACE               // 硬盘空间低报警事件
	EventIvsStoragefailure               EventIvs = C.EVENT_IVS_STORAGEFAILURE                // 存储错误事件
	EventIvsProfilealarmtransmit         EventIvs = C.EVENT_IVS_PROFILEALARMTRANSMIT          // 报警传输事件(对应 DEV_EVENT_PROFILE_ALARM_TRANSMIT_INFO)
	EventIvsVideostatic                  EventIvs = C.EVENT_IVS_VIDEOSTATIC                   // 视频静态检测事件(对应 DEV_EVENT_ALARM_VIDEOSTATIC_INFO)
	EventIvsVideotiming                  EventIvs = C.EVENT_IVS_VIDEOTIMING                   // 视频定时检测事件(对应 DEV_EVENT_ALARM_VIDEOTIMING_INFO)
	EventIvsHeatmap                      EventIvs = C.EVENT_IVS_HEATMAP                       // 热度图(对应 CFG_IVS_HEATMAP_INFO)
	EventIvsCitizenidcard                EventIvs = C.EVENT_IVS_CITIZENIDCARD                 // 身份证信息读取事件(对应 DEV_EVENT_ALARM_CITIZENIDCARD_INFO)
	EventIvsPicinfo                      EventIvs = C.EVENT_IVS_PICINFO                       // 图片信息事件(对应 DEV_EVENT_ALARM_PIC_INFO)
	EventIvsNetplaycheck                 EventIvs = C.EVENT_IVS_NETPLAYCHECK                  // 上网登记事件(对应 DEV_EVENT_ALARM_NETPLAYCHECK_INFO)
	EventIvsTrafficJamForbidInto         EventIvs = C.EVENT_IVS_TRAFFIC_JAM_FORBID_INTO       // 车辆拥堵禁入事件(对应 DEV_EVENT_ALARM_JAMFORBIDINTO_INFO)
	EventIvsSnapbytime                   EventIvs = C.EVENT_IVS_SNAPBYTIME                    // 定时抓图事件(对应DEV_EVENT_SNAPBYTIME)
	EventIvsPtzPreset                    EventIvs = C.EVENT_IVS_PTZ_PRESET                    // 云台转动到预置点事件(对应 DEV_EVENT_ALARM_PTZ_PRESET_INFO)
	EventIvsRfidInfo                     EventIvs = C.EVENT_IVS_RFID_INFO                     // 红外线检测信息事件(对应 DEV_EVENT_ALARM_RFID_INFO)
	EventIvsStandupdetection             EventIvs = C.EVENT_IVS_STANDUPDETECTION              // 人起立检测事件
	EventIvsQsytrafficcarweight          EventIvs = C.EVENT_IVS_QSYTRAFFICCARWEIGHT           // 交通卡口称重事件(对应 DEV_EVENT_QSYTRAFFICCARWEIGHT_INFO)
	EventIvsTrafficCompareplate          EventIvs = C.EVENT_IVS_TRAFFIC_COMPAREPLATE          // 卡口前后车牌合成事件(对应DEV_EVENT_TRAFFIC_COMPAREPLATE_INFO)
	EventIvsShootingscorerecognition     EventIvs = C.EVENT_IVS_SHOOTINGSCORERECOGNITION      // 打靶像机事件(对应 DEV_EVENT_SHOOTING_SCORE_RECOGNITION_INFO,CFG_IVS_SHOOTINGSCORERECOGNITION_INFO)
	EventIvsTrafficFcc                   EventIvs = C.EVENT_IVS_TRAFFIC_FCC                   // 加油站提枪、挂枪事件(对应 DEV_EVENT_TRAFFIC_FCC_INFO)
	EventIvsTrafficTransfinite           EventIvs = C.EVENT_IVS_TRAFFIC_TRANSFINITE           // 违章超限抓图上报事件,绍兴科技治超(对应 DEV_EVENT_TRAFFIC_TRANSFINITE_INFO)
	EventIvsSceneChange                  EventIvs = C.EVENT_IVS_SCENE_CHANGE                  // 场景变更事件(对应 DEV_ALRAM_SCENECHANGE_INFO,CFG_VIDEOABNORMALDETECTION_INFO)
	EventIvsLetrack                      EventIvs = C.EVENT_IVS_LETRACK                       // 简单跟踪事件(暂未有具体事件)
	EventIvsObjectAction                 EventIvs = C.EVENT_IVS_OBJECT_ACTION                 // 物体检测事件(暂未有具体事件)
	EventIvsTrafficAnalysePresnap        EventIvs = C.EVENT_IVS_TRAFFIC_ANALYSE_PRESNAP       // 预分析抓拍图片事件(对应 DEV_EVENT_TRAFFIC_ANALYSE_PRESNAP_INFO)
	EventAlarmEqstate                    EventIvs = C.EVENT_ALARM_EQSTATE                     // 智能插座电量状态上报(暂未有具体事件)
	EventIvsAlarmIpc                     EventIvs = C.EVENT_IVS_ALARM_IPC                     // DVR/NVR设备上的IPC报警(对应 DEV_EVENT_ALARM_IPC_INFO)
	EventIvsPosRecord                    EventIvs = C.EVENT_IVS_POS_RECORD                    // POS录像查询事件(暂未有具体事件)
	EventIvsNearDistanceDetection        EventIvs = C.EVENT_IVS_NEAR_DISTANCE_DETECTION       // 近距离接触事件(对应 DEV_EVENT_NEAR_DISTANCE_DETECTION_INFO)
	EventIvsObjectstructlizePerson       EventIvs = C.EVENT_IVS_OBJECTSTRUCTLIZE_PERSON       // 行人特征检测事件(对应 DEV_EVENT_OBJECTSTRUCTLIZE_PERSON_INFO)
	EventIvsObjectstructlizeNonmotor     EventIvs = C.EVENT_IVS_OBJECTSTRUCTLIZE_NONMOTOR     // 非机动车特征检测事件(对应 DEV_EVENT_OBJECTSTRUCTLIZE_NONMOTOR_INFO)
	EventIvsTumbleDetection              EventIvs = C.EVENT_IVS_TUMBLE_DETECTION              // 倒地报警事件(对应 DEV_EVENT_TUMBLE_DETECTION_INFO)
	EventIvsTrafficAll                   EventIvs = C.EVENT_IVS_TRAFFIC_ALL                   // 所有以traffic开头的事件,目前指的是
	// EVENT_IVS_TRAFFICCONTROL -> EVENT_TRAFFICSNAPSHOT
	// EVENT_IVS_TRAFFIC_RUNREDLIGHT -> EVENT_IVS_TRAFFIC_UNDERSPEED
	EventIvsVideoanalyse                  EventIvs = C.EVENT_IVS_VIDEOANALYSE                      // 所有智能分析事件
	EventIvsLinksd                        EventIvs = C.EVENT_IVS_LINKSD                            // LinkSD事件(对应 DEV_EVENT_LINK_SD)
	EventIvsVehicleanalyse                EventIvs = C.EVENT_IVS_VEHICLEANALYSE                    // 车辆特征检测分析(对应DEV_EVENT_VEHICLEANALYSE)
	EventIvsFlowrate                      EventIvs = C.EVENT_IVS_FLOWRATE                          // 流量使用情况事件(对应 DEV_EVENT_FLOWRATE_INFO)
	EventIvsAccessCtl                     EventIvs = C.EVENT_IVS_ACCESS_CTL                        // 门禁事件 (对应 DEV_EVENT_ACCESS_CTL_INFO)
	EventIvsSnapmanual                    EventIvs = C.EVENT_IVS_SNAPMANUAL                        // SnapManual事件(对应 DEV_EVENT_SNAPMANUAL)
	EventIvsTrafficEletaginfo             EventIvs = C.EVENT_IVS_TRAFFIC_ELETAGINFO                // RFID电子车牌标签事件(对应 DEV_EVENT_TRAFFIC_ELETAGINFO_INFO)
	EventIvsTrafficTiredphysiological     EventIvs = C.EVENT_IVS_TRAFFIC_TIREDPHYSIOLOGICAL        // 生理疲劳驾驶事件(对应 DEV_EVENT_TIREDPHYSIOLOGICAL_INFO)
	EventIvsTrafficBussharpturn           EventIvs = C.EVENT_IVS_TRAFFIC_BUSSHARPTURN              // 车辆急转报警事件(对应DEV_EVENT_BUSSHARPTURN_INFO)
	EventIvsCitizenPictureCompare         EventIvs = C.EVENT_IVS_CITIZEN_PICTURE_COMPARE           // 人证比对事件(对应 DEV_EVENT_CITIZEN_PICTURE_COMPARE_INFO)
	EventIvsTrafficTiredlowerhead         EventIvs = C.EVENT_IVS_TRAFFIC_TIREDLOWERHEAD            // 开车低头报警事件(对应DEV_EVENT_TIREDLOWERHEAD_INFO)
	EventIvsTrafficDriverlookaround       EventIvs = C.EVENT_IVS_TRAFFIC_DRIVERLOOKAROUND          // 开车左顾右盼报警事件(对应DEV_EVENT_DRIVERLOOKAROUND_INFO)
	EventIvsTrafficDriverleavepost        EventIvs = C.EVENT_IVS_TRAFFIC_DRIVERLEAVEPOST           // 开车离岗报警事件(对应DEV_EVENT_DRIVERLEAVEPOST_INFO)
	EventIvsManStandDetection             EventIvs = C.EVENT_IVS_MAN_STAND_DETECTION               // 立体视觉站立事件(对应DEV_EVENT_MANSTAND_DETECTION_INFO)
	EventIvsManNumDetection               EventIvs = C.EVENT_IVS_MAN_NUM_DETECTION                 // 立体视觉区域内人数统计事件(对应DEV_EVENT_MANNUM_DETECTION_INFO)
	EventIvsStereoNumberstat              EventIvs = C.EVENT_IVS_STEREO_NUMBERSTAT                 // 客流量统计事件(暂未有具体事件)
	EventIvsTrafficDriveryawn             EventIvs = C.EVENT_IVS_TRAFFIC_DRIVERYAWN                // 开车打哈欠事件(对应DEV_EVENT_DRIVERYAWN_INFO)
	EventIvsNumberstatPlan                EventIvs = C.EVENT_IVS_NUMBERSTAT_PLAN                   // 客流量统计计划(暂未有具体事件,球机使用,对应规则配置结构体 CFG_NUMBERSTAT_INFO)
	EventIvsHeatmapPlan                   EventIvs = C.EVENT_IVS_HEATMAP_PLAN                      // 热度图计划(暂未有具体事件,球机使用,对应规则配置结构体 CFG_IVS_HEATMAP_INFO)
	EventIvsCallnoanswered                EventIvs = C.EVENT_IVS_CALLNOANSWERED                    // 呼叫无答应事件
	EventIvsIgnoreinvite                  EventIvs = C.EVENT_IVS_IGNOREINVITE                      // 无视邀请事件
	EventIvsHumantrait                    EventIvs = C.EVENT_IVS_HUMANTRAIT                        // 人体特征事件(对应 DEV_EVENT_HUMANTRAIT_INFO)
	EventAlarmLeHeaddetection             EventIvs = C.EVENT_ALARM_LE_HEADDETECTION                // 乐橙人头检测事件,只用于订阅手机推送
	EventIvsFaceanalysis                  EventIvs = C.EVENT_IVS_FACEANALYSIS                      // 人脸分析事件 (暂未有具体事件)
	EventIvsTrafficTurnleftafterstraight  EventIvs = C.EVENT_IVS_TRAFFIC_TURNLEFTAFTERSTRAIGHT     // 左转不礼让直行事件(对应 DEV_EVENT_TURNLEFTAFTERSTRAIGHT_INFO)
	EventIvsTrafficBigbendsmallturn       EventIvs = C.EVENT_IVS_TRAFFIC_BIGBENDSMALLTURN          // 大弯小转事件(对应 DEV_EVENT_BIGBENDSMALLTURN_INFO)
	EventIvsRoadConstruction              EventIvs = C.EVENT_IVS_ROAD_CONSTRUCTION                 // 道路施工监测事件(对应DEV_EVENT_ROAD_CONSTRUCTION_INFO)
	EventIvsRoadBlock                     EventIvs = C.EVENT_IVS_ROAD_BLOCK                        // 路障检测事件(对应DEV_EVENT_ROAD_BLOCK_INFO)
	EventIvsTrafficQueuejump              EventIvs = C.EVENT_IVS_TRAFFIC_QUEUEJUMP                 // 车辆加塞事件(对应 DEV_EVENT_TRAFFIC_QUEUEJUMP_INFO)
	EventIvsVehicleSuspiciouscar          EventIvs = C.EVENT_IVS_VEHICLE_SUSPICIOUSCAR             // 嫌疑车辆事件(对应 DEV_EVENT_VEHICLE_SUSPICIOUSCAR_INFO)
	EventIvsTrafficTurnrightafterstraight EventIvs = C.EVENT_IVS_TRAFFIC_TURNRIGHTAFTERSTRAIGHT    // 右转不礼让直行事件(对应 DEV_EVENT_TURNRIGHTAFTERSTRAIGHT_INFO)
	EventIvsTrafficTurnrightafterpeople   EventIvs = C.EVENT_IVS_TRAFFIC_TURNRIGHTAFTERPEOPLE      // 右转不礼让直行行人(对应 DEV_EVENT_TURNRIGHTAFTERPEOPLE_INFO)
	EventIvsInstallCardreader             EventIvs = C.EVENT_IVS_INSTALL_CARDREADER                // 安装读卡器事件(对应 DEV_EVENT_INSTALL_CARDREADER_INFO)
	EventAlarmYaleDropboxBadtoken         EventIvs = C.EVENT_ALARM_YALE_DROPBOX_BADTOKEN           // Yale token失效事件，只用于订阅手机推送
	EventIvsAccOffSnap                    EventIvs = C.EVENT_IVS_ACC_OFF_SNAP                      // 车载设备断电前抓拍上传事件(对应 DEV_EVENT_ACC_OFF_SNAP_INFO)
	EveniIvsXrayDetection                 EventIvs = C.EVENI_IVS_XRAY_DETECTION                    // X光检测事件 (对应 DEV_EVENT_XRAY_DETECTION_INFO)
	EventIvsNotclearcar                   EventIvs = C.EVENT_IVS_NOTCLEARCAR                       // 未清车告警(对应 DEV_EVENT_NOTCLEARCAR_INFO)
	EventIvsSosaleart                     EventIvs = C.EVENT_IVS_SOSALEART                         // sos求救报警(对应 DEV_EVENT_SOSALEART_INFO)
	EventIvsOverload                      EventIvs = C.EVENT_IVS_OVERLOAD                          // 超载抓图(对应 DEV_EVENT_OVERLOAD_INFO)
	EventIvsNonworkingtime                EventIvs = C.EVENT_IVS_NONWORKINGTIME                    // 非工作时间告警(对应 DEV_EVENT_NONWORKINGTIME_INFO)
	EventIvsTrafficHighBeam               EventIvs = C.EVENT_IVS_TRAFFIC_HIGH_BEAM                 // 远光灯违章事件(对应 DEV_EVENT_TRAFFIC_HIGH_BEAM_INFO)
	EventIvsTrafficTruckforbid            EventIvs = C.EVENT_IVS_TRAFFIC_TRUCKFORBID               // 禁止货车事件(对应 DEV_EVENT_TRAFFICTRUCKFORBID_INFO)
	EventIvsDrivingwithoutcard            EventIvs = C.EVENT_IVS_DRIVINGWITHOUTCARD                // 无卡驾驶报警事件(对应 DEV_EVENT_DRIVINGWITHOUTCARD_INFO)
	EventIvsHighspeed                     EventIvs = C.EVENT_IVS_HIGHSPEED                         // 车辆超速报警事件(对应 DEV_EVENT_HIGHSPEED_INFO)
	EventIvsCrowddetection                EventIvs = C.EVENT_IVS_CROWDDETECTION                    // 人群密度检测事件(对应结构体 DEV_EVENT_CROWD_DETECTION_INFO)
	EventIvsTrafficCardistanceshort       EventIvs = C.EVENT_IVS_TRAFFIC_CARDISTANCESHORT          // 车间距过小报警事件(对应 DEV_EVENT_TRAFFIC_CARDISTANCESHORT_INFO)
	EventIvsPedestrianJunction            EventIvs = C.EVENT_IVS_PEDESTRIAN_JUNCTION               // 行人卡口事件(对应 DEV_EVENT_PEDESTRIAN_JUNCTION_INFO)
	EventIvsVehicleRecognition            EventIvs = C.EVENT_IVS_VEHICLE_RECOGNITION               // 车牌对比事件(中石化智慧加油站项目)(对应 DEV_EVENT_VEHICLE_RECOGNITION_INFO)
	EventIvsPassChange                    EventIvs = C.EVENT_IVS_PASS_CHANGE                       // 预置点图片变化事件 (对应 DEV_EVENT_PASS_CHANGE_INFO)
	EventIvsTrafficParkingSpacedetection  EventIvs = C.EVENT_IVS_TRAFFIC_PARKING_SPACEDETECTION    // 违停相机定制单球车位检测规则事件
	EventIvsTrafficWaitingarea            EventIvs = C.EVENT_IVS_TRAFFIC_WAITINGAREA               // 违章进入待行区事件(对应 DEV_EVENT_TRAFFIC_WAITINGAREA_INFO)
	EventIvsTrafficBan                    EventIvs = C.EVENT_IVS_TRAFFIC_BAN                       // 机动车违法禁令标识事件(对应 DEV_EVENT_TRAFFIC_BAN_INFO)
	EventIvsPosExchange                   EventIvs = C.EVENT_IVS_POS_EXCHANGE                      // POS机交易事件(对应 DEV_EVENT_POS_EXCHANGE_INFO)
	EventIvsStereoFightdetection          EventIvs = C.EVENT_IVS_STEREO_FIGHTDETECTION             // 立体行为分析打架/剧烈运动检测规则(仅用于规则配置，对应事件 EVENT_IVS_FIGHTDETECTION)
	EventIvsStereoDistanceDetection       EventIvs = C.EVENT_IVS_STEREO_DISTANCE_DETECTION         // 立体行为分析间距异常/人员靠近检测(仅用于规则配置，对应事件)
	EventIvsStereoStereofalldetection     EventIvs = C.EVENT_IVS_STEREO_STEREOFALLDETECTION        // 立体行为分析跌倒检测规则(仅用于规则配置，对应事件 EVENT_IVS_TUMBLE_DETECTION)
	EventIvsStereoStaydetection           EventIvs = C.EVENT_IVS_STEREO_STAYDETECTION              // 立体行为分析人员滞留检测规则(仅用于规则配置，对应事件 EVENT_IVS_STAYDETECTION)
	EventIvsBannerDetection               EventIvs = C.EVENT_IVS_BANNER_DETECTION                  // 拉横幅事件(对应 DEV_EVENT_BANNER_DETECTION_INFO)
	EventIvsNormalFightdetection          EventIvs = C.EVENT_IVS_NORMAL_FIGHTDETECTION             // 普通打架事件(只用于普通打架规则, 事件采用EVENT_IVS_FIGHTDETECTION)
	EventIvsElevatorAbnormal              EventIvs = C.EVENT_IVS_ELEVATOR_ABNORMAL                 // 电动扶梯运行异常事件 (对应DEV_EVENT_ELEVATOR_ABNORMAL_INFO)
	EventIvsNonmotordetect                EventIvs = C.EVENT_IVS_NONMOTORDETECT                    // 非机动车检测 (对应结构体 DEV_EVENT_NONMOTORDETECT_INFO)
	EventIvsVehicledetect                 EventIvs = C.EVENT_IVS_VEHICLEDETECT                     // 机动车检测 (只用于规则配置，事件采用EVENT_IVS_TRAFFICJUNCTION)
	EventIvsTrafficParkingB               EventIvs = C.EVENT_IVS_TRAFFIC_PARKING_B                 // 交通违章-B类违章停车(对应 DEV_EVENT_TRAFFIC_PARKING_B_INFO)
	EventIvsTrafficParkingC               EventIvs = C.EVENT_IVS_TRAFFIC_PARKING_C                 // 交通违章-C类违章停车(对应 DEV_EVENT_TRAFFIC_PARKING_C_INFO)
	EventIvsTrafficParkingD               EventIvs = C.EVENT_IVS_TRAFFIC_PARKING_D                 // 交通违章-D类违章停车(对应 DEV_EVENT_TRAFFIC_PARKING_D_INFO)
	EventIvssFaceattribute                EventIvs = C.EVENT_IVSS_FACEATTRIBUTE                    // IVSS人脸检测事件 (暂未有具体事件)
	EventIvssFacecompare                  EventIvs = C.EVENT_IVSS_FACECOMPARE                      // IVSS人脸识别事件 (暂未有具体事件)
	EventIvsFirewarning                   EventIvs = C.EVENT_IVS_FIREWARNING                       // 火警事件(对应 DEV_EVENT_FIREWARNING_INFO)
	EventIvsShoppresence                  EventIvs = C.EVENT_IVS_SHOPPRESENCE                      // 商铺占道经营事件(对应 DEV_EVENT_SHOPPRESENCE_INFO)
	EventIvsWastedumped                   EventIvs = C.EVENT_IVS_WASTEDUMPED                       // 垃圾违章倾倒事件(对应 DEV_EVENT_WASTEDUMPED_INFO)
	EventIvsSpilledmaterialDetection      EventIvs = C.EVENT_IVS_SPILLEDMATERIAL_DETECTION         // 抛洒物检测事件(对应 DEV_EVENT_SPILLEDMATERIAL_DETECTION_INFO)
	EventIvsStereoMannumDetection         EventIvs = C.EVENT_IVS_STEREO_MANNUM_DETECTION           // 立体行为分析人数异常检测 (仅用于规则配置，对应事件 EVENT_IVS_MAN_NUM_DETECTION)
	EventIvsDistanceDetection             EventIvs = C.EVENT_IVS_DISTANCE_DETECTION                // 异常间距事件 (对应 DEV_EVENT_DISTANCE_DETECTION_INFO)
	EventIvsTrafficNonmotorOverload       EventIvs = C.EVENT_IVS_TRAFFIC_NONMOTOR_OVERLOAD         // 非机动车超载事件 (对应 DEV_EVENT_TRAFFIC_NONMOTOR_OVERLOAD_INFO)
	EventIvsTrafficNonmotorWithoutsafehat EventIvs = C.EVENT_IVS_TRAFFIC_NONMOTOR_WITHOUTSAFEHAT   // 非机动车未戴安全帽事件 (对应 DEV_EVENT_TRAFFIC_NONMOTOR_WITHOUTSAFEHAT_INFO)
	EventIvsTrafficJamStopOnZebracrossing EventIvs = C.EVENT_IVS_TRAFFIC_JAM_STOP_ON_ZEBRACROSSING // 拥堵滞留斑马线事件 (对应 DEV_EVENT_TRAFFIC_JAM_STOP_ON_ZEBRACROSSING_INFO)
	EventIvsFlowbusiness                  EventIvs = C.EVENT_IVS_FLOWBUSINESS                      // 流动摊贩事件 (对应 DEV_EVENT_FLOWBUSINESS_INFO)
	EventIvsCityMotorparking              EventIvs = C.EVENT_IVS_CITY_MOTORPARKING                 // 城市机动车违停事件 (对应 DEV_EVENT_CITY_MOTORPARKING_INFO)
	EventIvsCityNonmotorparking           EventIvs = C.EVENT_IVS_CITY_NONMOTORPARKING              // 城市机非动车违停事件 (对应 DEV_EVENT_CITY_NONMOTORPARKING_INFO)
	EventIvsLanedepartureWarnning         EventIvs = C.EVENT_IVS_LANEDEPARTURE_WARNNING            // 车道偏移预警(对应 DEV_EVENT_LANEDEPARTURE_WARNNING_INFO)
	EventIvsForwardcollisionWarnning      EventIvs = C.EVENT_IVS_FORWARDCOLLISION_WARNNING         // 前向碰撞预警(对应 DEV_EVENT_FORWARDCOLLISION_WARNNING_INFO)
	EventIvsMaterialsstay                 EventIvs = C.EVENT_IVS_MATERIALSSTAY                     // 物料堆放事件(对应 DEV_EVENT_MATERIALSSTAY_INFO)
	EventIvsTrafficNonmotorHoldumbrella   EventIvs = C.EVENT_IVS_TRAFFIC_NONMOTOR_HOLDUMBRELLA     // 非机动车装载伞具(对应 DEV_EVENT_TRAFFIC_NONMOTOR_HOLDUMBRELLA_INFO)
	EventIvsJablotronAlarm                EventIvs = C.EVENT_IVS_JABLOTRON_ALARM                   // 客户报警产品
	EventIvsVideounfocusAlarm             EventIvs = C.EVENT_IVS_VIDEOUNFOCUS_ALARM                // 视频虚焦事件(对应DEV_EVENT_VIDEOUNFOCUS_INFO)
	EventIvsFloatingobjectDetection       EventIvs = C.EVENT_IVS_FLOATINGOBJECT_DETECTION          // 漂浮物检测事件 (对应 DEV_EVENT_FLOATINGOBJECT_DETECTION_INFO)
	EventIvsShipDetection                 EventIvs = C.EVENT_IVS_SHIP_DETECTION                    // 船舶检测事件 (对应 DEV_EVENT_SHIP_DETECTION_INFO)
	EventIvsAirplaneDetection             EventIvs = C.EVENT_IVS_AIRPLANE_DETECTION                // 飞机行为检测事件(对应 DEV_EVENT_AIRPLANE_DETECTION_INFO)
	EventIvsPhonecallDetect               EventIvs = C.EVENT_IVS_PHONECALL_DETECT                  // 打电话检测事件(对应 DEV_EVENT_PHONECALL_DETECT_INFO)
	EventIvsSmokingDetect                 EventIvs = C.EVENT_IVS_SMOKING_DETECT                    // 吸烟检测事件(对应 DEV_EVENT_SMOKING_DETECT_INFO)
	EventIvsRadarSpeedLimitAlarm          EventIvs = C.EVENT_IVS_RADAR_SPEED_LIMIT_ALARM           // 雷达限速报警事件(对应 DEV_EVENT_RADAR_SPEED_LIMIT_ALARM_INFO)
	EventIvsWaterLevelDetection           EventIvs = C.EVENT_IVS_WATER_LEVEL_DETECTION             // 水位检测事件 (对应 DEV_EVENT_WATER_LEVEL_DETECTION_INFO)
	EventIvsHoldUmbrella                  EventIvs = C.EVENT_IVS_HOLD_UMBRELLA                     // 违规撑伞检测事件 (对应 DEV_EVENT_HOLD_UMBRELLA_INFO)
	EventIvsGarbageExposure               EventIvs = C.EVENT_IVS_GARBAGE_EXPOSURE                  // 垃圾暴露检测事件 (对应 DEV_EVENT_GARBAGE_EXPOSURE_INFO)
	EventIvsDustbinOverFlow               EventIvs = C.EVENT_IVS_DUSTBIN_OVER_FLOW                 // 垃圾桶满溢检测事件 (对应 DEV_EVENT_DUSTBIN_OVER_FLOW_INFO)
	EventIvsDoorFrontDirty                EventIvs = C.EVENT_IVS_DOOR_FRONT_DIRTY                  // 门前脏乱检测事件 (对应 DEV_EVENT_DOOR_FRONT_DIRTY_INFO)
	EventIvsQueuestayDetection            EventIvs = C.EVENT_IVS_QUEUESTAY_DETECTION               // 排队滞留时间报警事件 (对应 DEV_EVENT_QUEUESTAY_DETECTION_INFO)
	EventIvsQueuenumDetection             EventIvs = C.EVENT_IVS_QUEUENUM_DETECTION                // 排队人数异常报警事件（对应 DEV_EVENT_QUEUENUM_DETECTION_INFO）
	EventIvsGenerategraphDetection        EventIvs = C.EVENT_IVS_GENERATEGRAPH_DETECTION           // 生成图规则事件（对应 DEV_EVENT_GENERATEGRAPH_DETECTION_INFO）
	EventIvsTrafficParkingManual          EventIvs = C.EVENT_IVS_TRAFFIC_PARKING_MANUAL            // 交通违章-手动取证(对应 DEV_EVENT_TRAFFIC_PARKING_MANUAL_INFO)
	EventIvsHelmetDetection               EventIvs = C.EVENT_IVS_HELMET_DETECTION                  // 安全帽检测事件(对应 DEV_EVENT_HELMET_DETECTION_INFO)
	EventIvsDepositDetection              EventIvs = C.EVENT_IVS_DEPOSIT_DETECTION                 // 包裹堆积程度检测事件(对应 DEV_EVENT_DEPOSIT_DETECTION_INFO)
	EventIvsHotspotWarning                EventIvs = C.EVENT_IVS_HOTSPOT_WARNING                   // 热点异常报警事件(对应 DEV_EVENT_HOTSPOT_WARNING_INFO)
	EventIvsWeighingPlatformDetection     EventIvs = C.EVENT_IVS_WEIGHING_PLATFORM_DETECTION       // 称重平台检测事件(对应 DEV_EVENT_WEIGHING_PLATFORM_DETECTION_INFO)
	EventIvsClassroomBehavior             EventIvs = C.EVENT_IVS_CLASSROOM_BEHAVIOR                // 课堂行为分析事件(对应 DEV_EVENT_CLASSROOM_BEHAVIOR_INFO)
	EventIvsVehicleDistanceNear           EventIvs = C.EVENT_IVS_VEHICLE_DISTANCE_NEAR             // 安全驾驶车距过近报警事件(对应 DEV_EVENT_VEHICLE_DISTANCE_NEAR_INFO)
	EventIvsTrafficDriverAbnormal         EventIvs = C.EVENT_IVS_TRAFFIC_DRIVER_ABNORMAL           // 驾驶员异常报警事件(对应 DEV_EVENT_TRAFFIC_DRIVER_ABNORMAL_INFO)
	EventIvsTrafficDriverChange           EventIvs = C.EVENT_IVS_TRAFFIC_DRIVER_CHANGE             // 驾驶员变更报警事件(对应 DEV_EVENT_TRAFFIC_DRIVER_CHANGE_INFO)
	EventIvsWorkclothesDetect             EventIvs = C.EVENT_IVS_WORKCLOTHES_DETECT                // 工装(安全帽/工作服等)检测事件(对应 DEV_EVENT_WORKCLOTHES_DETECT_INFO)
	EventIvsSecuritygatePersonalarm       EventIvs = C.EVENT_IVS_SECURITYGATE_PERSONALARM          // 安检门人员报警事件(对应 DEV_EVENT_SECURITYGATE_PERSONALARM_INFO)
	EventIvsStayAloneDetection            EventIvs = C.EVENT_IVS_STAY_ALONE_DETECTION              // 单人独处事件(对应 DEV_EVENT_STAY_ALONE_DETECTION_INFO)
	EventIvsTrafficRoadBlock              EventIvs = C.EVENT_IVS_TRAFFIC_ROAD_BLOCK                // 交通路障检测事件(对应 DEV_EVENT_TRAFFIC_ROAD_BLOCK_INFO)
	EventIvsTrafficRoadConstruction       EventIvs = C.EVENT_IVS_TRAFFIC_ROAD_CONSTRUCTION         // 交通道路施工检测事件(对应 DEV_EVENT_TRAFFIC_ROAD_CONSTRUCTION_INFO)
	EventIvsXrayDetectByobject            EventIvs = C.EVENT_IVS_XRAY_DETECT_BYOBJECT              // X光按物体检测规则配置, 对应事件 EVENI_IVS_XRAY_DETECTION
	EventIvsWorkstatdetection             EventIvs = C.EVENT_IVS_WORKSTATDETECTION                 // 作业统计事件(对应 DEV_EVENT_WORKSTATDETECTION_INFO)
	EventIvsInfraredblock                 EventIvs = C.EVENT_IVS_INFRAREDBLOCK                     // 红外阻断事件(对应 DEV_EVENT_INFRAREDBLOCK_INFO)
	EventIvsFeatureAbstract               EventIvs = C.EVENT_IVS_FEATURE_ABSTRACT                  // 特征提取事件(对应 DEV_EVENT_FEATURE_ABSTRACT_INFO)
	EventIvsIntelliShelf                  EventIvs = C.EVENT_IVS_INTELLI_SHELF                     // 智能补货事件(对应 DEV_EVENT_INTELLI_SHELF_INFO)
	EventIvsPanoramaShot                  EventIvs = C.EVENT_IVS_PANORAMA_SHOT                     // 全景抓拍事件(对应 DEV_EVENT_PANORAMA_SHOT_INFO)
	EventAlarmSmartmotionHuman            EventIvs = C.EVENT_ALARM_SMARTMOTION_HUMAN               // 智能视频移动侦测事件(人)，目前只用于订阅手机推送, 无具体事件
	EventAlarmSmartmotionVehicle          EventIvs = C.EVENT_ALARM_SMARTMOTION_VEHICLE             // 智能视频移动侦测事件(车),目前只用于订阅手机推送, 无具体事件
	EventIvsCarDrivingInOut               EventIvs = C.EVENT_IVS_CAR_DRIVING_IN_OUT                // 车辆驶入驶出状态事件(对应 DEV_EVENT_CAR_DRIVING_IN_OUT_INFO)
	EventIvsParkingspaceStatus            EventIvs = C.EVENT_IVS_PARKINGSPACE_STATUS               // 停车位状态事件(对应 DEV_EVENT_PARKINGSPACE_STATUS_INFO)
	EventIvsViolentThrowDetection         EventIvs = C.EVENT_IVS_VIOLENT_THROW_DETECTION           // 暴力抛物检测(对应 DEV_EVENT_VIOLENT_THROW_DETECTION_INFO)
	EventIvsTramcarsectionsDetection      EventIvs = C.EVENT_IVS_TRAMCARSECTIONS_DETECTION         // 矿车超挂报警事件(对应 DEV_EVENT_TRAMCARSECTIONS_DETECTION_INFO)
	EventIvsAlarmBoxAlarm                 EventIvs = C.EVENT_IVS_ALARM_BOX_ALARM                   // 报警盒通道的触发报警事件, 目前只用于订阅手机推送
	EventIvsFaceComparision               EventIvs = C.EVENT_IVS_FACE_COMPARISION                  // 人脸比对事件, 专用于手机推送的人脸识别事件, 目前只用于订阅手机推送
	EventIvsFacebodyDetect                EventIvs = C.EVENT_IVS_FACEBODY_DETECT                   // 人像检测事件（对应 DEV_EVENT_FACEBODY_DETECT_INFO）
	EventIvsFacebodyAnalyse               EventIvs = C.EVENT_IVS_FACEBODY_ANALYSE                  // 人像识别事件（对应 DEV_EVENT_FACEBODY_ANALYSE_INFO）
	EventIvsGasstationVehicleDetect       EventIvs = C.EVENT_IVS_GASSTATION_VEHICLE_DETECT         // 加油站车辆检测事件 (对应 DEV_EVENT_GASSTATION_VEHICLE_DETECT_INFO)
	EventIvsCongestionDetection           EventIvs = C.EVENT_IVS_CONGESTION_DETECTION              // 道路场景车辆拥堵报警事件（对应 DEV_EVENT_CONGESTION_DETECTION_INFO）
	EventIvsVehiclelimitDetection         EventIvs = C.EVENT_IVS_VEHICLELIMIT_DETECTION            // 停车场场景下停车车辆上限报警（对应 DEV_EVENT_VEHICLELIMIT_DETECTION_INFO）
	EventIvsAnimalDetection               EventIvs = C.EVENT_IVS_ANIMAL_DETECTION                  // 动物检测事件,(对应 DEV_EVENT_ANIMAL_DETECTION_INFO)
	EventIvsShopWindowPost                EventIvs = C.EVENT_IVS_SHOP_WINDOW_POST                  // 橱窗张贴事件 (对应 DEV_EVENT_SHOP_WINDOW_POST_INFO)
	EventIvsShopSignAbnormal              EventIvs = C.EVENT_IVS_SHOP_SIGN_ABNORMAL                // 店招异常事件 (对应 DEV_EVENT_SHOP_SIGN_ABNORMAL_INFO)
	EventIvsBreedDetection                EventIvs = C.EVENT_IVS_BREED_DETECTION                   // 智慧养殖检测事件 (对应 DEV_EVENT_BREED_DETECTION_INFO)
	EventIvsAirportVehicleDetect          EventIvs = C.EVENT_IVS_AIRPORT_VEHICLE_DETECT            // 机场智能保障车辆检测事件 (对应 DEV_EVENT_AIRPORT_VEHICLE_DETECT_INFO)
	EventIvsPigTemperatureDetect          EventIvs = C.EVENT_IVS_PIG_TEMPERATURE_DETECT            // 智慧养殖猪体温检测 (只用于规则配置)
	EventIvsManCarCoexistance             EventIvs = C.EVENT_IVS_MAN_CAR_COEXISTANCE               // 人车共存事件 (对应 DEV_EVENT_MAN_CAR_COEXISTANCE_INFO)
	EventIvsHighTossDetect                EventIvs = C.EVENT_IVS_HIGH_TOSS_DETECT                  // 高空抛物检测(对应DEV_EVENT_HIGH_TOSS_DETECT_INFO)
	EventIvsElectricGloveDetect           EventIvs = C.EVENT_IVS_ELECTRIC_GLOVE_DETECT             // 电力检测手套检测事件(对应DEV_EVENT_ELECTRIC_GLOVE_DETECT_INFO)
	EventIvsElectricLadderDetect          EventIvs = C.EVENT_IVS_ELECTRIC_LADDER_DETECT            // 电力检测梯子检测事件(对应DEV_EVENT_ELECTRIC_LADDER_DETECT_INFO)
	EventIvsElectricCurtainDetect         EventIvs = C.EVENT_IVS_ELECTRIC_CURTAIN_DETECT           // 电力检测布幔检测事件(对应DEV_EVENT_ELECTRIC_CURTAIN_DETECT_INFO)
	EventIvsElectricFenceDetect           EventIvs = C.EVENT_IVS_ELECTRIC_FENCE_DETECT             // 电力检测围栏检测事件(对应DEV_EVENT_ELECTRIC_FENCE_DETECT_INFO)
	EventIvsElectricSignboardDetect       EventIvs = C.EVENT_IVS_ELECTRIC_SIGNBOARD_DETECT         // 电力检测标识牌检测事件(对应DEV_EVENT_ELECTRIC_SIGNBOARD_DETECT_INFO)
	EventIvsElectricBeltDetect            EventIvs = C.EVENT_IVS_ELECTRIC_BELT_DETECT              // 电力检测安全带检测事件(对应DEV_EVENT_ELECTRIC_BELT_DETECT_INFO)
	EventIvsRadarLineDetection            EventIvs = C.EVENT_IVS_RADAR_LINE_DETECTION              // 雷达警戒线/绊线检测(对应DEV_EVENT_RADAR_LINE_DETECTION_INFO)
	EventIvsRadarRegionDetection          EventIvs = C.EVENT_IVS_RADAR_REGION_DETECTION            // 雷达警戒区检测事件(对应 DEV_EVENT_RADAR_REGION_DETECTION_INFO)
	EventIvsAudioIntensity                EventIvs = C.EVENT_IVS_AUDIO_INTENSITY                   // 异常音事件(对应 DEV_EVENT_AUDIO_INTENSITY_INFO)
	EventIvsParkingLotStatusDetection     EventIvs = C.EVENT_IVS_PARKING_LOT_STATUS_DETECTION      // 室外停车位状态检测 (对应 DEV_EVENT_PARKING_LOT_STATUS_DETECTION_INFO)
	EventIvsVehicleCompare                EventIvs = C.EVENT_IVS_VEHICLE_COMPARE                   // (只用于规则配置)
	EventIvsDregsUncovered                EventIvs = C.EVENT_IVS_DREGS_UNCOVERED                   // 渣土车未遮盖载货检测事件(对应 DEV_EVENT_DREGS_UNCOVERED_INFO)
	EventIvsWalkDetection                 EventIvs = C.EVENT_IVS_WALK_DETECTION                    // 走动检测事件(对应 DEV_EVENT_WALK_DETECTION_INFO)
	EventIvsBackToDetection               EventIvs = C.EVENT_IVS_BACK_TO_DETECTION                 // 背对检测事件(对应 DEV_EVENT_BACK_TO_DETECTION_INFO)
	EventIvsWriteOnTheBoardDetection      EventIvs = C.EVENT_IVS_WRITE_ON_THE_BOARD_DETECTION      // 板书检测事件(对应 DEV_EVENT_WRITE_ON_THE_BOARD_DETECTION_INFO)
	EventIvsSmartKitchenClothesDetection  EventIvs = C.EVENT_IVS_SMART_KITCHEN_CLOTHES_DETECTION   // 智慧厨房穿着检测事件（对不戴口罩、厨师帽以及颜色不符合规定的厨师服进行报警）（对应 DEV_EVENT_SMART_KITCHEN_CLOTHES_DETECTION_INFO ）
)
